"""Render agent reports to self-contained HTML."""

import html
import os

from . import db

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "reports")

_CSS = """
body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;max-width:820px;margin:2rem auto;
padding:0 1rem;color:#1a1a1a}
h1{margin-bottom:.2rem}.sub{color:#666;margin-top:0}
.cards{display:flex;flex-wrap:wrap;gap:.75rem;margin:1.2rem 0}
.card{flex:1 1 130px;background:#f6f8fa;border:1px solid #e3e6ea;border-radius:10px;padding:.8rem 1rem}
.card .n{font-size:1.5rem;font-weight:700}.card .l{color:#666;font-size:.8rem}
.recs li{margin:.4rem 0}table{border-collapse:collapse;width:100%}
td,th{border-bottom:1px solid #eee;padding:.4rem;text-align:left}
.tag{background:#eef;border-radius:6px;padding:.1rem .5rem;font-size:.8rem}
footer{color:#999;font-size:.8rem;margin-top:2rem}
"""


def _card(n, label):
    return f'<div class="card"><div class="n">{html.escape(str(n))}</div><div class="l">{html.escape(label)}</div></div>'


def render(report: dict, narrative: str) -> str:
    os.makedirs(OUT_DIR, exist_ok=True)
    if report["kind"] == "performance":
        title = f"Performance — {report['company']}"
        cards = "".join([
            _card(f"{report['revenue']:,.0f}", "Revenue (THB)"),
            _card(f"{report['profit']:,.0f}", "Profit (THB)"),
            _card(f"{report['margin_pct']}%", "Margin"),
            _card(f"{report['growth_pct']}%" if report['growth_pct'] is not None else "—", "Growth vs prev"),
            _card(report["sales_count"], "Sales logged"),
        ])
        extra = _cat_table("Top revenue categories", report["top_sales_categories"]) + \
                _cat_table("Top expense categories", report["top_expense_categories"])
        sub = f"Last {report['period_days']} days · {report['period_start']} → {report['period_end']}"
    else:
        title = f"Market trends — {report['province']}"
        cards = "".join([
            _card(report["total_companies"], "Companies"),
            _card(report["clients"], "Clients"),
            _card(report["contactable"], "Contactable"),
            _card(report["with_social"], "With social"),
        ])
        extra = _cat_table("By venue type", report["by_venue_type"])
        sub = "Directory-level opportunity scan"

    recs = "".join(f"<li>{html.escape(r)}</li>" for r in report.get("recommendations", []))
    body = f"""<!doctype html><html><head><meta charset="utf-8">
<title>{html.escape(title)}</title><style>{_CSS}</style></head><body>
<h1>{html.escape(title)}</h1><p class="sub">{html.escape(sub)}</p>
<div class="cards">{cards}</div>
<h3>Recommended steps</h3><ul class="recs">{recs}</ul>
<h3>Agent summary</h3><pre style="white-space:pre-wrap">{html.escape(narrative)}</pre>
{extra}
<footer>Generated by KrobJob agent · {html.escape(db.now())}</footer>
</body></html>"""

    slug = report.get("company", report.get("province", "report")).replace(" ", "_")
    path = os.path.join(OUT_DIR, f"{report['kind']}_{slug}.html")
    with open(path, "w", encoding="utf-8") as f:
        f.write(body)
    return path


def _cat_table(title, pairs):
    if not pairs:
        return ""
    rows = "".join(
        f"<tr><td>{html.escape(str(k))}</td><td>{(f'{v:,.0f}' if isinstance(v,(int,float)) else html.escape(str(v)))}</td></tr>"
        for k, v in pairs)
    return f"<h3>{html.escape(title)}</h3><table>{rows}</table>"
